import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
import Footer from "@/components/Footer";
import TanstackProvider from "@/providers/TanstackProvider";
import ReduxProvider from "@/providers/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <TanstackProvider>
        <ReduxProvider>
          <Navbar />
          {/* <HeroSection /> */}
          {children}
          <Footer />
        </ReduxProvider>
      </TanstackProvider>
      </body>
    </html>
  );
}
